name: Build Windows Executable

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if (Test-Path "requirements.txt") {
            pip install -r requirements.txt
        }
      shell: pwsh

    - name: Build executable
      run: |
        pyinstaller --onefile --name win64 main.py
        echo "Build output:"
        dir dist

    - name: Upload executable artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-executable
        path: dist/win64.exe
        if-no-files-found: warn
        compression-level: 6
        overwrite: true